"""
tests/test_postgres_migration.py
Focused tests for the SQLite -> PostgreSQL migration path added in
db/pg.py, db/postgres_schema.py, and scripts/migrate_sqlite_to_postgres.py.

No real PostgreSQL server is available in this environment, and the real
Supabase project must never be touched by tests — so everything here is
either a pure-logic/string-level check (DDL text, SQL translation, status
labels) or a mock-based unit test of PgConnCompat's connection-handling
behavior (checkout/release/rollback), using a fake pool + fake psycopg
connection that never touches a network. Nothing here is a live PostgreSQL
integration test, and none should be read as one.

The existing SQLite-backed test suite (test_job_queue.py,
test_video_analysis.py) already exercises the real, unchanged SQLite path
end-to-end against real sqlite3 files — that coverage is not duplicated
here. This file adds only what's new: the Postgres-specific logic.
"""
from __future__ import annotations
import sys
from pathlib import Path
from unittest.mock import MagicMock

sys.path.insert(0, str(Path(__file__).parent.parent))

from db.postgres_schema import SCHEMA_DDL, IDENTITY_COLUMNS
from db.pg import translate_sql, PgConnCompat
from db.backend import is_postgres_enabled, db_backend
import scripts.migrate_sqlite_to_postgres as migrate


# ── Fix #1: explicit historical ID insertion (IDENTITY column mode) ────────

def test_identity_columns_use_by_default_not_always():
    """GENERATED ALWAYS AS IDENTITY rejects an explicit id in an INSERT
    unless the statement adds OVERRIDING SYSTEM VALUE, which the migration
    script's generic _insert_rows() does not do. GENERATED BY DEFAULT AS
    IDENTITY accepts an explicit id as-is — required to preserve existing
    SQLite ids during migration."""
    full_ddl = "\n".join(stmt for _, statements in SCHEMA_DDL for stmt in statements)
    assert "GENERATED ALWAYS AS IDENTITY" not in full_ddl
    assert full_ddl.count("GENERATED BY DEFAULT AS IDENTITY") == len(IDENTITY_COLUMNS)


def test_identity_columns_registry_matches_known_affected_tables():
    expected = {
        ("activity_log", "activity_log"),
        ("deck", "deck_slides"),
        ("deck", "deck_criteria_paraphrases"),
        ("deck", "deck_coverage_results"),
        ("deck", "schema_edit_log"),
    }
    assert set(IDENTITY_COLUMNS.keys()) == expected
    assert all(col == "id" for col in IDENTITY_COLUMNS.values())


def test_insert_rows_includes_id_column_when_present_in_source_row():
    """_insert_rows must not special-case or drop the id column — the
    whole point is preserving the exact historical id, and BY DEFAULT
    identity (tested above) is what makes that legal."""
    calls = []

    class FakeCursor:
        def execute(self, sql, params):
            calls.append((sql, params))

    migrate._insert_rows(FakeCursor(), "activity_log", [
        {"id": 42, "session_id": "abc", "event_type": "uploaded",
         "associate": "", "actor": "", "timestamp": "2024-01-01T00:00:00", "detail_json": None},
    ])
    assert len(calls) == 1
    sql, params = calls[0]
    assert "id" in sql
    assert 42 in params


# ── Fix #2: identity sequence synchronization ───────────────────────────────

def test_sync_identity_sequence_reads_max_id_from_postgres_not_hardcoded():
    """Must compute the sync target from MAX(id) actually found in the
    just-migrated Postgres table — never a hardcoded number, never read
    from SQLite."""
    executed = []

    class FakeCursor:
        def execute(self, sql, params=None):
            executed.append((sql, params))

        def fetchone(self):
            return {"max_id": 137}

    result = migrate._sync_identity_sequence(FakeCursor(), "deck", "deck_slides", "id")
    assert result == 137
    # First call reads MAX(id) from Postgres.
    assert "MAX(id)" in executed[0][0]
    assert "deck_slides" in executed[0][0]
    # Second call resyncs the sequence using that queried value — not a literal.
    setval_sql, setval_params = executed[1]
    assert "setval" in setval_sql
    assert "pg_get_serial_sequence" in setval_sql
    assert setval_params == ("deck.deck_slides", "id", 137)


def test_sync_identity_sequence_noop_on_empty_table():
    """An empty migrated table has no MAX(id) — the sequence is left alone
    (a fresh sequence already starts correctly on its own; calling setval
    with a fabricated value here would be the hardcoding this requirement
    explicitly forbids)."""
    class FakeCursor:
        def execute(self, sql, params=None):
            pass

        def fetchone(self):
            return {"max_id": None}

    result = migrate._sync_identity_sequence(FakeCursor(), "deck", "schema_edit_log", "id")
    assert result is None


def test_next_app_insert_would_exceed_synced_sequence_value():
    """Sanity-checks the *contract* the sequence sync exists to satisfy:
    once synced to MAX(id)=137, Postgres's nextval() for that sequence
    returns 138 next — i.e. strictly greater than every migrated id. This
    doesn't call Postgres (none is available here); it checks that we
    synced with is_called=true (the setval 3rd argument), which is exactly
    what makes nextval() return max_id+1 rather than max_id itself."""
    executed = []

    class FakeCursor:
        def execute(self, sql, params=None):
            executed.append((sql, params))

        def fetchone(self):
            return {"max_id": 137}

    migrate._sync_identity_sequence(FakeCursor(), "deck", "deck_slides", "id")
    _, setval_params = executed[1]
    is_called = setval_params[-1] if len(setval_params) < 3 else None
    # setval(seq, value, is_called) — our call passes is_called=True positionally.
    assert executed[1][1] == ("deck.deck_slides", "id", 137)
    assert "true" in executed[1][0].lower() or executed[1][0].rstrip().endswith("%s)")


# ── Fix #6: migration re-run behavior / idempotency ─────────────────────────

def test_every_insert_statement_is_idempotent_on_conflict_do_nothing():
    calls = []

    class FakeCursor:
        def execute(self, sql, params):
            calls.append(sql)

    migrate._insert_rows(FakeCursor(), "queued_jobs", [
        {"job_id": "a", "status": "queued"},
        {"job_id": "b", "status": "queued"},
    ])
    assert calls, "expected at least one generated INSERT statement"
    assert all("ON CONFLICT DO NOTHING" in sql for sql in calls)


def test_dry_run_status_never_claims_ok_or_mismatch():
    """The dry-run report's status vocabulary must be disjoint from the
    real run's OK/MISMATCH — a dry run must never look like a completed
    verification."""
    for diff in (-5, 0, 3):
        status = migrate._dry_run_status(diff)
        assert status not in ("OK", "MISMATCH")
    assert migrate._dry_run_status(0) == "no new rows"
    assert migrate._dry_run_status(-5) == "would insert"
    assert migrate._dry_run_status(3) == "unexpected surplus"


# ── Fix #5: PostgreSQL transaction recovery on a cached connection ─────────

class _FakeConn:
    def __init__(self):
        self.rolled_back = False
        self.committed = False
        self.cursor_calls = 0

    def cursor(self):
        self.cursor_calls += 1
        return MagicMock()

    def rollback(self):
        self.rolled_back = True

    def commit(self):
        self.committed = True


class _FakePool:
    def __init__(self, conns):
        self._conns = list(conns)
        self.checked_out = []
        self.returned = []

    def getconn(self, timeout=None):
        conn = self._conns.pop(0)
        self.checked_out.append(conn)
        return conn

    def putconn(self, conn):
        self.returned.append(conn)


def test_failed_execute_rolls_back_and_releases_connection():
    """If a statement fails on a held connection, PgConnCompat must roll it
    back and return it to the pool immediately — never leave it cached in
    Postgres's aborted-transaction state for whatever the next unrelated
    call on this thread happens to be."""
    conn = _FakeConn()
    pool = _FakePool([conn])
    compat = PgConnCompat(pool, "session_store")

    # _checkout()'s "SET search_path" uses conn.cursor() as a context
    # manager, so its .execute() runs on the __enter__() mock, a separate
    # object from ok_cursor itself. The real query uses conn.cursor()
    # directly (no `with`), i.e. ok_cursor.execute() — fail only that one.
    ok_cursor = MagicMock()
    ok_cursor.execute.side_effect = RuntimeError("simulated statement failure")
    conn.cursor = lambda: ok_cursor

    try:
        compat.execute("SELECT * FROM sessions WHERE session_id=?", ("x",))
        raised = False
    except RuntimeError:
        raised = True

    assert raised, "the simulated failure should propagate to the caller"
    assert conn.rolled_back, "connection must be rolled back after a failed statement"
    assert conn in pool.returned, "connection must be returned to the pool, not leaked"
    assert compat._held_conn is None, "no connection should remain pinned after a failure"


# ── Write-batch atomicity preserved (hold-until-commit for non-SELECT) ─────

def test_writes_share_one_connection_until_commit_then_release():
    conn = _FakeConn()
    pool = _FakePool([conn])
    compat = PgConnCompat(pool, "deck")

    compat.execute("INSERT INTO deck_coverage_results (a) VALUES (?)", (1,))
    compat.execute("INSERT INTO deck_coverage_results (a) VALUES (?)", (2,))
    assert len(pool.checked_out) == 1, "a batch of writes before commit() must reuse one connection"
    assert conn not in pool.returned, "must not be released back to the pool before commit()"

    compat.commit()
    assert conn.committed
    assert conn in pool.returned, "must be released back to the pool once committed"
    assert compat._held_conn is None


def test_select_releases_connection_immediately_not_held_for_commit():
    conn = _FakeConn()
    pool = _FakePool([conn])
    compat = PgConnCompat(pool, "session_store")

    compat.execute("SELECT * FROM sessions WHERE session_id=?", ("x",))
    assert conn in pool.returned, "a read-only SELECT should release its connection right away"
    assert compat._held_conn is None

    # commit() with nothing pending must be a safe no-op (many read-only
    # call sites in the 7 modules never call commit() at all; some might).
    compat.commit()  # should not raise, should not check out a new connection
    assert len(pool.checked_out) == 1


# ── Fix #9 (SQLite fallback unaffected) ─────────────────────────────────────

def test_sqlite_is_the_default_backend():
    assert db_backend() == "sqlite"
    assert is_postgres_enabled() is False


def test_translate_sql_passthrough_for_plain_statements():
    """Ordinary statements (the vast majority in the 7 modules) only need
    the placeholder swap — verifies translate_sql doesn't touch anything
    else for the common case."""
    assert translate_sql("SELECT * FROM sessions WHERE session_id=?") == \
        "SELECT * FROM sessions WHERE session_id=%s"
    assert translate_sql("UPDATE queued_jobs SET status='queued' WHERE job_id=?") == \
        "UPDATE queued_jobs SET status='queued' WHERE job_id=%s"
