"""
db/postgres_schema.py
PostgreSQL DDL mirroring the 7 SQLite store modules' schemas exactly — same
tables, columns, and constraints, translated only where SQLite/Postgres
syntax genuinely differs:
  - INTEGER PRIMARY KEY AUTOINCREMENT -> INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  - REAL -> DOUBLE PRECISION
  - PRAGMA statements dropped (Postgres doesn't need WAL mode / foreign_keys=ON;
    FK enforcement is always on)

IDENTITY columns use "GENERATED BY DEFAULT AS IDENTITY", not "GENERATED
ALWAYS". "ALWAYS" rejects any INSERT that supplies an explicit value for
that column (exactly what the one-time migration script needs to do, to
preserve every row's existing SQLite id) unless the statement adds
OVERRIDING SYSTEM VALUE. "BY DEFAULT" allows an explicit id to be inserted
as-is with no statement change, while still auto-generating one via the
sequence for every ordinary application-level insert that omits it (every
runtime INSERT in the 7 store modules already omits `id` — see
save_slide/save_paraphrase/save_coverage_results/log_event — so normal
app behavior is unaffected). See IDENTITY_COLUMNS below and
scripts/migrate_sqlite_to_postgres.py's post-migration sequence sync,
which is required precisely because "BY DEFAULT" does NOT auto-advance
the sequence when an explicit id is supplied.

Each module gets its OWN Postgres schema (namespace), named after the
module. That's what lets a bare table named `sessions` exist in both
session_store and kalvium_auth without colliding in the same Postgres
database — each module's connection has its search_path pointed at just
its own schema (+public), exactly mirroring "each module owned its own
SQLite file" — so none of the 7 modules' CRUD call sites need to
reference a schema-qualified name.

NOTE — our auth.py module's Postgres schema is named "kalvium_auth", NOT
"auth". A managed Postgres provider (e.g. Supabase) commonly pre-provisions
its OWN "auth" schema for its own built-in user-management system
(confirmed live against a real Supabase project: it already contains 22
tables, including ones literally named `users` and `sessions`, with a
completely different structure than ours). Using the reserved name "auth"
here would silently target — or collide with — that schema instead of
creating our own. "kalvium_auth" is deliberately app-specific and must
never be renamed back to the bare word "auth".

Statement order within each schema's list is parent-before-child so
foreign keys always resolve on a fresh database:
  kalvium_auth:  users -> sessions
  deck:  deck_schemas -> deck_slides / deck_criteria -> paraphrases /
         call_links / coverage_results / schema_edit_log
"""
from __future__ import annotations

SESSION_STORE = [
    """CREATE TABLE IF NOT EXISTS sessions (
        session_id       TEXT PRIMARY KEY,
        status           TEXT NOT NULL,
        label            TEXT DEFAULT '',
        source_type      TEXT DEFAULT '',
        source_url       TEXT DEFAULT '',
        created_at       TEXT,
        completed_at     TEXT,
        duration_seconds DOUBLE PRECISION,
        overall_score    DOUBLE PRECISION,
        grade            TEXT,
        error            TEXT,
        lead_sheet_json  TEXT,
        report_json      TEXT
    )""",
    "CREATE INDEX IF NOT EXISTS idx_sessions_label ON sessions(label)",
    "CREATE INDEX IF NOT EXISTS idx_sessions_created_at ON sessions(created_at)",
    # Added for the Audit History filter/export feature (history_filters.py)
    # — see session_store.py's init_db() for the matching SQLite versions
    # and the full reasoning (why Lead Stage/Payment Done/Prospect
    # ID/Lead Number are deliberately NOT indexed here).
    "CREATE INDEX IF NOT EXISTS idx_sessions_completed_at ON sessions(completed_at)",
    "CREATE INDEX IF NOT EXISTS idx_sessions_demo_date ON sessions ((lead_sheet_json::jsonb ->> 'Demo Date'))",
    "CREATE INDEX IF NOT EXISTS idx_sessions_tl_name ON sessions ((lead_sheet_json::jsonb ->> 'TL Name'))",
]

ACTIVITY_LOG = [
    """CREATE TABLE IF NOT EXISTS activity_log (
        id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        session_id   TEXT,
        associate    TEXT DEFAULT '',
        event_type   TEXT NOT NULL,
        actor        TEXT DEFAULT '',
        timestamp    TEXT NOT NULL,
        detail_json  TEXT
    )""",
    "CREATE INDEX IF NOT EXISTS idx_activity_session ON activity_log(session_id)",
    "CREATE INDEX IF NOT EXISTS idx_activity_associate ON activity_log(associate)",
    "CREATE INDEX IF NOT EXISTS idx_activity_event ON activity_log(event_type)",
    "CREATE INDEX IF NOT EXISTS idx_activity_timestamp ON activity_log(timestamp)",
    # Composite: latest_tracker_lead_owner_by_session() filters on
    # event_type='pushed_to_tracker' AND sorts by timestamp DESC — the
    # dashboard calls it on every load. Covers both in one index scan.
    "CREATE INDEX IF NOT EXISTS idx_activity_event_timestamp ON activity_log(event_type, timestamp)",
]

KALVIUM_AUTH = [
    """CREATE TABLE IF NOT EXISTS users (
        user_id         TEXT PRIMARY KEY,
        email           TEXT UNIQUE NOT NULL,
        name            TEXT NOT NULL,
        password_hash   TEXT NOT NULL,
        password_salt   TEXT NOT NULL,
        role            TEXT NOT NULL DEFAULT 'associate',
        associate_name  TEXT DEFAULT '',
        status          TEXT NOT NULL DEFAULT 'active',
        created_at      TEXT NOT NULL,
        last_login_at   TEXT
    )""",
    """CREATE TABLE IF NOT EXISTS sessions (
        token       TEXT PRIMARY KEY,
        user_id     TEXT NOT NULL REFERENCES users(user_id),
        created_at  TEXT NOT NULL,
        expires_at  TEXT NOT NULL
    )""",
    "CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id)",
]

ASSOCIATE_ROSTER = [
    """CREATE TABLE IF NOT EXISTS associate_roster (
        name       TEXT PRIMARY KEY,
        added_at   TEXT NOT NULL
    )""",
]

JOB_QUEUE = [
    """CREATE TABLE IF NOT EXISTS queued_jobs (
        job_id        TEXT PRIMARY KEY,
        source_type   TEXT NOT NULL,
        label         TEXT DEFAULT '',
        actor         TEXT DEFAULT '',
        filename      TEXT DEFAULT '',
        duration_hint TEXT DEFAULT '',
        payload_json  TEXT NOT NULL,
        status        TEXT NOT NULL DEFAULT 'queued',
        batch_id      TEXT DEFAULT '',
        order_index   INTEGER DEFAULT 0,
        created_at    TEXT,
        started_at    TEXT,
        completed_at  TEXT,
        error         TEXT
    )""",
    "CREATE INDEX IF NOT EXISTS idx_queued_jobs_status ON queued_jobs(status)",
    "CREATE INDEX IF NOT EXISTS idx_queued_jobs_order ON queued_jobs(order_index)",
]

SARVAM_STT_JOBS = [
    """CREATE TABLE IF NOT EXISTS sarvam_stt_jobs (
        session_id       TEXT PRIMARY KEY,
        sarvam_job_id    TEXT DEFAULT '',
        status           TEXT NOT NULL DEFAULT 'submitted',
        wav_path         TEXT DEFAULT '',
        duration_seconds DOUBLE PRECISION,
        num_segments     INTEGER DEFAULT 1,
        retry_count      INTEGER DEFAULT 0,
        error_message    TEXT DEFAULT '',
        cancel_requested INTEGER NOT NULL DEFAULT 0,
        created_at       TEXT,
        updated_at       TEXT
    )""",
    "CREATE INDEX IF NOT EXISTS idx_sarvam_jobs_status ON sarvam_stt_jobs(status)",
]

VIDEO_AUDITS = [
    """CREATE TABLE IF NOT EXISTS video_audits (
        id                 TEXT PRIMARY KEY,
        linked_session_id  TEXT DEFAULT '',
        source_url         TEXT DEFAULT '',
        label              TEXT DEFAULT '',
        actor              TEXT DEFAULT '',
        status             TEXT NOT NULL DEFAULT 'queued',
        duration_seconds   DOUBLE PRECISION,
        created_at         TEXT,
        completed_at       TEXT,
        error              TEXT,
        screenshots_json   TEXT,
        summary_json       TEXT,
        preprocessing_json TEXT
    )""",
    "CREATE INDEX IF NOT EXISTS idx_video_audits_session ON video_audits(linked_session_id)",
]

DECK = [
    """CREATE TABLE IF NOT EXISTS deck_schemas (
        deck_id         TEXT PRIMARY KEY,
        deck_slug       TEXT NOT NULL,
        version_major   INTEGER NOT NULL DEFAULT 1,
        schema_patch    INTEGER NOT NULL DEFAULT 0,
        deck_name       TEXT NOT NULL,
        status          TEXT NOT NULL DEFAULT 'draft',
        scoring_weights TEXT NOT NULL DEFAULT '{"behavioral_layer":0.55,"deck_coverage_layer":0.45}',
        source_filename TEXT,
        slide_count     INTEGER DEFAULT 0,
        total_criteria  INTEGER DEFAULT 0,
        created_at      TEXT NOT NULL,
        created_by      TEXT DEFAULT 'system',
        promoted_at     TEXT,
        changelog       TEXT NOT NULL DEFAULT '[]'
    )""",
    """CREATE TABLE IF NOT EXISTS deck_slides (
        id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        deck_id         TEXT NOT NULL REFERENCES deck_schemas(deck_id),
        slide_number    INTEGER NOT NULL,
        title           TEXT,
        raw_text        TEXT,
        speaker_notes   TEXT,
        slide_category  TEXT,
        section_id      TEXT,
        UNIQUE(deck_id, slide_number)
    )""",
    """CREATE TABLE IF NOT EXISTS deck_criteria (
        criterion_id        TEXT PRIMARY KEY,
        deck_id             TEXT NOT NULL REFERENCES deck_schemas(deck_id),
        slide_number        INTEGER NOT NULL,
        label               TEXT NOT NULL,
        explanation         TEXT NOT NULL,
        importance          TEXT NOT NULL DEFAULT 'should',
        slide_section       TEXT DEFAULT 'general',
        embedding_json      TEXT,
        detection_threshold DOUBLE PRECISION NOT NULL DEFAULT 0.72,
        disabled            INTEGER NOT NULL DEFAULT 0,
        human_override      TEXT,
        custom_notes        TEXT DEFAULT '',
        display_order       INTEGER DEFAULT 0
    )""",
    """CREATE TABLE IF NOT EXISTS deck_criteria_paraphrases (
        id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        criterion_id    TEXT NOT NULL REFERENCES deck_criteria(criterion_id),
        paraphrase_text TEXT NOT NULL,
        embedding_json  TEXT
    )""",
    """CREATE TABLE IF NOT EXISTS deck_call_links (
        session_id  TEXT NOT NULL,
        deck_id     TEXT NOT NULL REFERENCES deck_schemas(deck_id),
        linked_at   TEXT NOT NULL,
        PRIMARY KEY (session_id, deck_id)
    )""",
    """CREATE TABLE IF NOT EXISTS deck_coverage_results (
        id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        session_id      TEXT NOT NULL,
        deck_id         TEXT NOT NULL,
        criterion_id    TEXT NOT NULL,
        covered         INTEGER NOT NULL DEFAULT 0,
        best_similarity DOUBLE PRECISION DEFAULT 0.0,
        best_window_idx INTEGER DEFAULT -1,
        detection_mode  TEXT DEFAULT 'direct',
        evaluated_at    TEXT NOT NULL,
        UNIQUE(session_id, deck_id, criterion_id)
    )""",
    """CREATE TABLE IF NOT EXISTS schema_edit_log (
        id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        deck_id      TEXT NOT NULL,
        criterion_id TEXT,
        field_name   TEXT NOT NULL,
        old_value    TEXT,
        new_value    TEXT,
        edited_by    TEXT DEFAULT 'admin',
        edited_at    TEXT NOT NULL
    )""",
    "CREATE INDEX IF NOT EXISTS idx_criteria_deck ON deck_criteria(deck_id)",
    "CREATE INDEX IF NOT EXISTS idx_coverage_session ON deck_coverage_results(session_id)",
    "CREATE INDEX IF NOT EXISTS idx_paraphrases_criterion ON deck_criteria_paraphrases(criterion_id)",
    # get_active_deck() filters WHERE status='active' on every call.
    "CREATE INDEX IF NOT EXISTS idx_deck_schemas_status ON deck_schemas(status)",
]

# schema_name -> ordered DDL statements (parent tables before child tables).
# Cross-schema FKs don't exist anywhere in this app, so only within-schema
# ordering matters — each module's own list above is already parent-first.
#
# "kalvium_auth", not "auth" — see the NOTE at the top of this file. Never
# change this back to the bare word "auth"; that name is reserved by
# Supabase (and likely other managed Postgres providers) for their own
# built-in auth system's schema.
SCHEMA_DDL = [
    ("kalvium_auth", KALVIUM_AUTH),
    ("session_store", SESSION_STORE),
    ("activity_log", ACTIVITY_LOG),
    ("associate_roster", ASSOCIATE_ROSTER),
    ("job_queue", JOB_QUEUE),
    ("sarvam_stt_jobs", SARVAM_STT_JOBS),
    ("video_audits", VIDEO_AUDITS),
    ("deck", DECK),
]

_BY_NAME = dict(SCHEMA_DDL)

# (schema, table) -> identity column name, for every table whose `id` is
# GENERATED BY DEFAULT AS IDENTITY. The one-time migration script uses this
# to know which tables need their Postgres sequence resynced to
# MAX(id) after historical rows are inserted with explicit ids — "BY
# DEFAULT" (unlike a plain SERIAL) never advances the sequence itself when
# an explicit value is supplied, so without this step the next ordinary
# app-level insert (which omits `id`) would try to reuse an id that
# already exists among the migrated rows.
IDENTITY_COLUMNS: dict[tuple[str, str], str] = {
    ("activity_log", "activity_log"): "id",
    ("deck", "deck_slides"): "id",
    ("deck", "deck_criteria_paraphrases"): "id",
    ("deck", "deck_coverage_results"): "id",
    ("deck", "schema_edit_log"): "id",
}


def apply_schema(conn, schema: str) -> None:
    """Create the given module's Postgres schema + all its tables/indexes
    if they don't already exist, then point the connection's search_path
    at it. `conn` only needs an `.execute(sql)` + `.commit()` method — works
    for both db.pg.PgConnCompat and a raw psycopg connection/cursor."""
    if schema not in _BY_NAME:
        raise ValueError(f"db/postgres_schema.py: unknown schema {schema!r}")
    conn.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')
    conn.execute(f'SET search_path TO "{schema}", public')
    for stmt in _BY_NAME[schema]:
        conn.execute(stmt)
    conn.commit()
