"""
scripts/migrate_sqlite_to_postgres.py

One-time ETL: copies every row from the 7 existing SQLite databases into the
PostgreSQL database configured via DATABASE_URL — without modifying or
deleting any SQLite file, and without switching the running app's
DB_BACKEND (that stays "sqlite" until this succeeds and you flip it
yourself — see CLOUD_MIGRATION_PLAN.md).

Usage:
    PYTHONPATH="$(pwd)" python3 scripts/migrate_sqlite_to_postgres.py [--dry-run]

Safety guarantees:
  - The ENTIRE real migration (schema creation + every row insert +
    identity-sequence sync + the verification report) runs inside a single
    PostgreSQL transaction. Any failure, or any row-count mismatch found
    during verification, rolls back that whole transaction — Postgres is
    left exactly as it was before the script ran. Never a partially
    migrated database.
  - Schema is created/verified before any row is inserted, parent tables
    before child tables (auth: users -> sessions; deck: deck_schemas ->
    deck_slides/deck_criteria -> paraphrases/call_links/coverage_results) —
    see db/postgres_schema.py.
  - Idempotent: every insert uses `ON CONFLICT DO NOTHING` against the
    same primary/unique keys as the source SQLite table, so re-running
    this script after a failure (or a no-op re-run once already migrated)
    never duplicates rows. (Re-running does NOT pick up rows that changed
    in SQLite since a previous run — only new ones — which is expected for
    a one-time cutover script.)
  - Historical ids are preserved exactly (activity_log, deck_slides,
    deck_criteria_paraphrases, deck_coverage_results, schema_edit_log use
    GENERATED BY DEFAULT AS IDENTITY — see db/postgres_schema.py — which
    accepts an explicit id as-is). After inserting each such table's rows,
    this script resyncs that table's Postgres identity sequence to
    MAX(id) actually found in the just-migrated Postgres table (never
    hardcoded, never read from SQLite) — see _sync_identity_sequence() —
    so the next ordinary application insert (which omits `id`) is
    guaranteed to receive an id greater than every migrated one.
  - --dry-run performs schema preflight only and reports the CURRENT
    (pre-migration) Postgres row counts next to SQLite's — it never
    inserts a row, never claims a row-count match, and always rolls back,
    including the schema/table creation. It is a preflight check, not a
    substitute for the real run's post-migration verification.
  - DATABASE_URL is read once from settings and used only to open a
    connection. It is never logged, printed, or included in any output —
    every error message below is a fixed, generic string.
"""
from __future__ import annotations
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from config.settings import get_settings                       # noqa: E402
from db.postgres_schema import SCHEMA_DDL, IDENTITY_COLUMNS    # noqa: E402

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:
    psycopg = None
    dict_row = None

DATA = ROOT / "data"

# (sqlite_file, table, pg_schema) — parents before children within each schema.
TABLES = [
    (DATA / "auth.db",             "users",                      "auth"),
    (DATA / "auth.db",             "sessions",                   "auth"),
    (DATA / "sessions.db",         "sessions",                   "session_store"),
    (DATA / "activity_log.db",     "activity_log",               "activity_log"),
    (DATA / "associate_roster.db", "associate_roster",           "associate_roster"),
    (DATA / "job_queue.db",        "queued_jobs",                "job_queue"),
    (DATA / "video_audits.db",     "video_audits",               "video_audits"),
    (DATA / "decks.db",            "deck_schemas",               "deck"),
    (DATA / "decks.db",            "deck_slides",                "deck"),
    (DATA / "decks.db",            "deck_criteria",              "deck"),
    (DATA / "decks.db",            "deck_criteria_paraphrases",  "deck"),
    (DATA / "decks.db",            "deck_call_links",            "deck"),
    (DATA / "decks.db",            "deck_coverage_results",      "deck"),
    (DATA / "decks.db",            "schema_edit_log",            "deck"),
]


def _redact(exc: Exception) -> str:
    """Never let a raw driver exception (which can embed the DSN) reach
    stdout — only its class name is safe to print."""
    return type(exc).__name__


def _sqlite_rows(db_path: Path, table: str) -> list[dict]:
    if not db_path.exists():
        return []
    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    try:
        return [dict(r) for r in conn.execute(f"SELECT * FROM {table}").fetchall()]
    finally:
        conn.close()


def _sqlite_count(db_path: Path, table: str) -> int:
    if not db_path.exists():
        return 0
    conn = sqlite3.connect(str(db_path))
    try:
        row = conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()
        return row[0] if row else 0
    finally:
        conn.close()


def _pg_count(cur, table: str) -> int:
    """Actually queries PostgreSQL — never a stand-in value. Caller must
    have already SET search_path to the right schema on this cursor."""
    cur.execute(f"SELECT COUNT(*) AS n FROM {table}")
    return cur.fetchone()["n"]


def _insert_rows(cur, table: str, rows: list[dict]) -> None:
    if not rows:
        return
    cols = list(rows[0].keys())
    col_list = ", ".join(cols)
    placeholders = ", ".join(["%s"] * len(cols))
    sql = f"INSERT INTO {table} ({col_list}) VALUES ({placeholders}) ON CONFLICT DO NOTHING"
    for row in rows:
        cur.execute(sql, [row[c] for c in cols])


def _sync_identity_sequence(cur, schema: str, table: str, id_col: str) -> int | None:
    """Resyncs `table`'s Postgres identity sequence to MAX(id_col) as found
    in the just-migrated Postgres table itself (never hardcoded, never
    taken from SQLite) — required because GENERATED BY DEFAULT AS IDENTITY
    does not auto-advance its sequence when an explicit id is supplied.
    Returns the max id synced to, or None if the table is empty (nothing
    to sync — a fresh sequence already starts correctly on its own).
    Caller must have already SET search_path to `schema` on this cursor."""
    cur.execute(f"SELECT MAX({id_col}) AS max_id FROM {table}")
    max_id = cur.fetchone()["max_id"]
    if max_id is None:
        return None
    cur.execute(
        "SELECT setval(pg_get_serial_sequence(%s, %s), %s, true)",
        (f"{schema}.{table}", id_col, max_id),
    )
    return max_id


def _dry_run_status(diff: int) -> str:
    """Pure status label for a preflight row — never "OK"/"MISMATCH", which
    are reserved for the real run's post-migration verification, so a
    dry-run report can never be mistaken for a claim that data matches."""
    if diff < 0:
        return "would insert"
    if diff == 0:
        return "no new rows"
    return "unexpected surplus"


def _print_report(rows, title: str, note: str = "") -> None:
    print("\n" + "=" * 78)
    print(title)
    print("=" * 78)
    print(f"{'schema.table':<42}{'sqlite':>8}{'postgres':>10}{'diff':>8}  status")
    print("-" * 78)
    for schema, table, s_n, p_n, diff, status in rows:
        print(f"{schema + '.' + table:<42}{s_n:>8}{p_n:>10}{diff:>8}  {status}")
    print("-" * 78)
    if note:
        print(note)


def _run_dry_run(conn) -> int:
    """Preflight only: verifies the schema can be created and reports the
    CURRENT (pre-migration) PostgreSQL row counts next to SQLite's — every
    count is a real query against PostgreSQL, never a stand-in. Inserts
    nothing. Always rolls back, including the schema/table creation, so it
    leaves no trace. This is NOT the migration's verification step — it
    cannot be, since dry-run writes nothing to compare against; see the
    real run's post-migration verification for that."""
    report_rows: list[tuple] = []
    with conn.cursor() as cur:
        for schema, statements in SCHEMA_DDL:
            cur.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')
            cur.execute(f'SET search_path TO "{schema}", public')
            for stmt in statements:
                cur.execute(stmt)

        for db_path, table, schema in TABLES:
            sqlite_n = _sqlite_count(db_path, table)
            cur.execute(f'SET search_path TO "{schema}", public')
            pg_n = _pg_count(cur, table)  # real query — table exists from the preflight DDL above
            diff = pg_n - sqlite_n
            report_rows.append((schema, table, sqlite_n, pg_n, diff, _dry_run_status(diff)))

    conn.rollback()
    _print_report(
        report_rows,
        title="PREFLIGHT REPORT (dry run — schema check only, no data written)",
        note=(
            "This is a preflight check, not post-migration verification: 'postgres' above is\n"
            "the CURRENT row count in the target database (usually 0 on a fresh database) before\n"
            "any data is written, not a claim that it matches SQLite. Run without --dry-run to\n"
            "actually migrate and get the real post-migration verification report.\n"
            "The transaction was rolled back — including schema/table creation — so nothing\n"
            "was left behind."
        ),
    )
    print("\nDry run complete — no changes were committed.")
    return 0


def _run_real_migration(conn) -> int:
    report_rows: list[tuple] = []
    with conn.cursor() as cur:
        # 1) Schema first — parent tables before child tables, per schema.
        for schema, statements in SCHEMA_DDL:
            cur.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')
            cur.execute(f'SET search_path TO "{schema}", public')
            for stmt in statements:
                cur.execute(stmt)

        # 2) Data + identity-sequence sync — same parent-before-child order as TABLES.
        for db_path, table, schema in TABLES:
            rows = _sqlite_rows(db_path, table)
            cur.execute(f'SET search_path TO "{schema}", public')
            _insert_rows(cur, table, rows)
            id_col = IDENTITY_COLUMNS.get((schema, table))
            if id_col:
                _sync_identity_sequence(cur, schema, table, id_col)

        # 3) Verification — every table, evaluated inside the same
        #    still-open transaction, BEFORE any commit decision. Both
        #    counts are real queries; nothing here is assumed or faked.
        for db_path, table, schema in TABLES:
            sqlite_n = _sqlite_count(db_path, table)
            cur.execute(f'SET search_path TO "{schema}", public')
            pg_n = _pg_count(cur, table)
            diff = pg_n - sqlite_n
            status = "OK" if diff == 0 else "MISMATCH"
            report_rows.append((schema, table, sqlite_n, pg_n, diff, status))

        mismatched = any(r[-1] == "MISMATCH" for r in report_rows)
        if mismatched:
            conn.rollback()
            _print_report(
                report_rows,
                title="VERIFICATION REPORT (migration rolled back)",
                note="(Transaction was rolled back — counts above reflect the attempted state,\n"
                     "not what was actually persisted in PostgreSQL.)",
            )
            print("\nMIGRATION FAILED — one or more tables had a row-count mismatch. "
                  "The PostgreSQL transaction was rolled back; no partial data was "
                  "left behind. SQLite data is untouched.")
            return 1

        conn.commit()

    _print_report(report_rows, title="VERIFICATION REPORT (migration committed)")
    print("\nMIGRATION SUCCEEDED — all tables verified, transaction committed. "
          "SQLite files are untouched and remain available as a rollback/backup. "
          "The running app still uses SQLite until DB_BACKEND is explicitly set "
          "to 'postgres'.")
    return 0


def run(dry_run: bool = False) -> int:
    if psycopg is None:
        print("ERROR: the 'psycopg' package is not installed. Run: pip install \"psycopg[binary]\"")
        return 1

    database_url = get_settings().database_url
    if not database_url:
        print("ERROR: DATABASE_URL is not configured. Aborting — nothing was touched.")
        return 1

    try:
        conn = psycopg.connect(database_url, autocommit=False, row_factory=dict_row, connect_timeout=10)
    except Exception as exc:
        print(f"ERROR: could not connect to PostgreSQL ({_redact(exc)}). Aborting — nothing was touched.")
        return 1

    try:
        if dry_run:
            return _run_dry_run(conn)
        return _run_real_migration(conn)
    except Exception as exc:
        conn.rollback()
        print(f"ERROR during migration ({_redact(exc)}). Transaction rolled back — "
              f"PostgreSQL was left unchanged. SQLite data is untouched.")
        return 1
    finally:
        conn.close()


if __name__ == "__main__":
    sys.exit(run(dry_run="--dry-run" in sys.argv))
